<?php 
/**
 * Amazon Related Products
 * Author: Alain Gonzalez
 * Plugin URI: http://web-argument.com/amazon-related-products-wordpress-plugin/
*/

$amzrp_regions = array(
    "com"=>__("United States"),
    "ca"=>__("Canada"),
    "cn"=>__("China"),
    "de"=>__("Germany"),
    "es"=>__("Spain"),
    "fr"=>__("France"),
    "it"=>__("Italy"),
    "jp"=>__("Japan"),
    "uk"=>__("United Kingdom")
);

$amzrp_search_index_arr = array(
						 "ca" => array(
										"All",
										"Baby",
										"Blended",
										"Books",
										"Classical",
										"DVD",
										"Electronics",
										"ForeignBooks",
										"HealthPersonalCare",
										"KindleStore",
										"Kitchen",
										"LawnGarden",
										"Music",
										"PetSupplies",
										"Software",
										"SoftwareVideoGames",
										"VHS",
										"Video",
										"VideoGames"
										),
										
						"cn"=>	array(	
										"All",
										"Apparel",
										"Appliances",														                  
										"Automotive",
										"Baby",
										"Beauty",
										"Books",
										"Electronics",
										"Grocery",
										"HealthPersonalCare",
										"Home",
										"HomeImprovement",
										"Jewelry",
										"KindleStore",
										"Misc",
										"Music",
										"OfficeProducts",
										"PetSupplies",
										"Photo",
										"Shoes",
										"Software",
										"SportingGoods",
										"Toys",
										"Video",
										"VideoGames",
										"Watches"
										),
										
						"de"=> array(
										"All",
										"Apparel",
										"Automotive",
										"Baby",
										"Blended",
										"Beauty",
										"Books",
										"Classical",
										"DVD",
										"Electronics",
										"ForeignBooks",
										"Grocery",
										"HealthPersonalCare",
										"HomeGarden",
										"Jewelry",
										"KindleStore",
										"Kitchen",
										"Lighting",
										"Magazines",
										"Marketplace",
										"MP3Downloads",
										"Music",
										"MusicalInstruments",
										"MusicTracks",
										"OfficeProducts",
										"OutdoorLiving",
										"Outlet",
										"PCHardware",
										"Photo",
										"Software",
										"SoftwareVideoGames",
										"SportingGoods",
										"Tools",
										"Toys",
										"VHS",
										"Video",
										"VideoGames",
										"Watches"							
										),
						
					"es"=> array(
										"All",
										"Automotive",
										"Baby",
										"Books",
										"DVD",
										"Electronics",
										"ForeignBooks",
										"KindleStore",
										"Kitchen",
										"MP3Downloads",
										"Music",
										"Shoes",
										"Software",
										"Toys",
										"VideoGames",
										"Watches"
										),
					"fr"=> array(
																
										"All",
										"Apparel",
										"Automotive",
										"Baby",
										"Beauty",
										"Blended",
										"Books",
										"Classical",
										"DVD",															
										"Electronics",
										"ForeignBooks",
										"HealthPersonalCare",
										"HomeImprovement",
										"Jewelry",
										"KindleStore",
										"Kitchen",
										"Lighting",
										"MP3Downloads",
										"Music",
										"MusicalInstruments",
										"MusicTracks",
										"OfficeProducts",
										"Outlet",
										"PetSupplies",
										"Shoes",
										"Software",
										"SoftwareVideoGames",
										"VHS",
										"Video",
										"VideoGames",
										"Watches"
										),
					"it"=> array(
										"All",
										"Automotive",
										"Baby",
										"Books",
										"DVD",											
										"Electronics",
										"ForeignBooks",
										"Garden",
										"KindleStore",
										"Kitchen",
										"Lighting",
										"MP3Downloads",
										"Music",
										"Shoes",
										"Software",
										"Toys",
										"VideoGames",
										"Watches"
										),																										
					"jp"=> array(
										"All",
										"Apparel",
										"Appliances",
										"Automotive",
										"Baby",
										"Beauty",
										"Blended",
										"Books",
										"Classical",
										"DVD",
										"Electronics",
										"ForeignBooks",
										"Grocery",
										"HealthPersonalCare",
										"Hobbies",
										"HomeImprovement",
										"Jewelry",
										"KindleStore",
										"Kitchen",
										"Marketplace",
										"MobileApps",
										"MP3Downloads",
										"Music",
										"MusicalInstruments",
										"MusicTracks",
										"OfficeProducts",
										"Shoes",
										"Software",
										"SportingGoods",
										"Toys",
										"VHS",
										"Video",
										"VideoGames",
										"Watches"
										),
					"uk"=> array(
					
										"All",
										"Apparel",
										"Automotive",
										"Baby",						
										"Beauty",
										"Blended",
										"Books",
										"Classical",
										"DVD",
										"Electronics",
										"Grocery",
										"HealthPersonalCare",
										"HomeGarden",
										"Jewelry",
										"KindleStore",
										"Kitchen",
										"Lighting",
										"Marketplace",
										"MP3Downloads",
										"Music",
										"MusicalInstruments",
										"MusicTracks",
										"OfficeProducts",
										"OutdoorLiving",
										"Outlet",
										"Shoes",
										"Software",
										"SoftwareVideoGames",
										"Toys",
										"VHS",
										"Video",
										"VideoGames",
										"Watches"
										),						
					
					"com"=> array(						
										"All",
										"Apparel",
										"Appliances",
										"ArtsAndCrafts",
										"Automotive",
										"Baby",
										"Beauty",
										"Blended",
										"Books",
										"Classical",
										"Collectibles",
										"DigitalMusic",
										"Grocery",
										"DVD",
										"Electronics",
										"HealthPersonalCare",
										"HomeGarden",
										"Industrial",
										"Jewelry",
										"KindleStore",
										"Kitchen",
										"LawnGarden",
										"Magazines",
										"Marketplace",
										"Merchants",
										"Miscellaneous",
										"MobileApps",
										"MP3Downloads",
										"Music",
										"MusicalInstruments",
										"MusicTracks",
										"OfficeProducts",
										"OutdoorLiving",
										"PCHardware",
										"PetSupplies",
										"Photo",
										"Shoes",
										"Software",
										"SportingGoods",
										"Tools",
										"Toys",
										"UnboxVideo",
										"VHS",
										"Video",
										"VideoGames",
										"Watches",
										"Wireless",
										"WirelessAccessories"
										)
);


function amzrp_get_search_index($region = "com"){	

	global $amzrp_search_index_arr;
	$search_index_group = $search_index_arr['com'];
	
	if (array_key_exists ($region, $amzrp_search_index_arr)) {
		$search_index_group = $amzrp_search_index_arr[$region];
	} 
	
	return $search_index_group;	
	
}

function amzrp_get_region($id){
	global $amzrp_regions;
	$region = $amzrp_regions[$id];
	if (isset ($region)){
		return $region;
	} else {
		return false;
	}	
}

?>